### ISSUE TITLE
evaluating functions in scope

### ISSUE THREAD

**Issue by Hifilo** [Froskk/inline-math#1]
Hello, I think this is the only inline math extension in vscode so thanks for making this!

Maybe these features are beyond the scope of this extension, but:

1) is there a way for the extension to include math done within variables?

`5*5` works but `x = 5*5` doesn't

2) is a way to have this work with p5js/processing math functions?

here is an example:

```js
  createCanvas(800, 800);



//this works as intended
`5*5` // gives inline value 25

//these don't show values
    r = TWO_PI * 12; //would show numerical result of 75.398

    let sinR = sin(r); //would show numerical value 
    Center = width / 2; //would show 400


```

**Comment by rcoopr** [comment]
Thanks for the interest. I believe your first point already works, see below. If you are finding that it doesn't show a result, you can select the text you want to evaluate and if it can be parsed by [MathJs](https://mathjs.org/) then it will show a result.

The 2nd point is reminding me of [Quokka](https://quokkajs.com/) - I will have to look and see how they accomplish it, but I think it might be difficult to implement

![image](https://github.com/rcoopr/inline-math/assets/37559715/ae346ed9-5ea7-4764-a2ea-1b886f97d3ef)

**Comment by Hifilo** [comment]
I see. It shows at the cursor. Didn't realize that.

Funny enough, I tried running Quokka with p5.js, but doesn't seem to work properly(atleast for me). I think it has to do with the fact that draw() is constantly adding to itself. I'll make an issue with Quokka, perhaps I'm doing something wrong.

In my case I don't need to print strings, or anything complex, but I do need to confirm the math though. That's why I thought your extension might work as an alternative to get a quick calculation of an angle or something.

I appreciate you seeing if its possible

**Comment by ZA0068** [comment]
please add an option where we can substitute the operation with the result where `1+1` becomes `2` automatically or pressing certain keyboard combo like ctrl + alt + M

**Comment by rcoopr** [comment]
This would require evaluating the js/ts code in situe whereas this extension only evaluates each individual line (and substrings) of it, so this goes beyond the current scope of the extension

**Comment by ZA0068** [comment]
> This would require evaluating the js/ts code in site whereas this extension only evaluates each individual line (and substrings) of it, so this goes beyond the current scope of the extension

actually not m, but pressing the = sign after the expression will replace the value.
