### ISSUE TITLE
Inability to correctly process math with relatively large powers

### ISSUE THREAD

**Issue by jsonDoge** [Froskk/inline-math#3]
`10*10^18 + 50*10^18 - 10 >= 60*10^18` returns true when should be false.

![image](https://github.com/user-attachments/assets/d41733d9-d1df-41a2-8b14-d829dac89bb2)

**Comment by rcoopr** [comment]
math evaluation is done with `mathjs` and the error is due to limitations with large numbers in that library. If there is a better library that could be used I'd be happy to look into switching
